dist: xenail
language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: "make test"

after_success:
  - bumpversion --config-file .bumpversion.cfg --verbose patch
  - git push
