dist: xenail
language: python
python:
- '3.7'
install:
- pip install .
- pip install -r requirements.txt
script:
- make utest
- pwd
- echo "Hello 003"
- ls -lR
- pwd
- cd ontheroad_ui
- cd ..
- pwd
#- cd ontheroad_ui && yarn install
  #- yarn run build
  #- cd
- echo "Hello 004"
after_success:
- git config --global user.email "johnstratoudakis@egmail.com"
- git config --global user.name "Bumpversion after CI"
- bumpversion --config-file .bumpversion.cfg --verbose patch
- chmod 600 travis_deploy_key
- eval `ssh-agent -s`
- ssh-add travis_deploy_key
- git config --global push.default simple
- git remote add deploy $(git remote -v | sed -nre 's#^origin.*https://([^/]*)/([^
  ]*) *.*push.*#git@\1:\2#p')
- git push deploy HEAD:master
- python setup.py sdist
- pip install twine
- twine upload --verbose --config-file .pypirc-bot -r pypi dist/*
before_install:
- openssl aes-256-cbc -K $encrypted_3bc2bd3e7847_key -iv $encrypted_3bc2bd3e7847_iv
  -in secret-files.tar.enc -out secret-files.tar -d
- tar xvf secret-files.tar
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  keep_history: true
  local_dir: ontheroad_ui/build
  on:
    branch: master
