dist: xenail
language: python
python:
- '3.7'
install:
- pip install .
- pip install -r requirements.txt
sudo: required
notifications:
  webhooks:
    urls:
      - https://app.johnstratoudakis.com/hooks/redeploy
    on_success: always # default: always
services:
- docker
script:
- make unit_tests
- git config --global user.email "johnstratoudakis@egmail.com"
- git config --global user.name "Bumpversion after CI"
- bumpversion --config-file .bumpversion.cfg --verbose patch
- chmod 600 travis_deploy_key
- eval `ssh-agent -s`
- ssh-add travis_deploy_key
- git config --global push.default simple
- git remote add deploy $(git remote -v | sed -nre 's#^origin.*https://([^/]*)/([^
  ]*) *.*push.*#git@\1:\2#p')
- git push deploy HEAD:master
- docker build -t johnstratoudakis/ontheroad_flask:latest ./OnTheRoad
- docker build -t johnstratoudakis/ontheroad_ui:latest ./ontheroad_ui
#- cd ontheroad_ui
#- yarn install
#- yarn run build
- cd ..
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker push johnstratoudakis/ontheroad_flask:latest
- docker push johnstratoudakis/ontheroad_ui:latest
#- git config --global user.email "johnstratoudakis@egmail.com"
#- git config --global user.name "Bumpversion after CI"
#- bumpversion --config-file .bumpversion.cfg --verbose patch
#- chmod 600 travis_deploy_key
#- eval `ssh-agent -s`
#- ssh-add travis_deploy_key
#- git config --global push.default simple
#- git remote add deploy $(git remote -v | sed -nre 's#^origin.*https://([^/]*)/([^
#  ]*) *.*push.*#git@\1:\2#p')
#- git push deploy HEAD:master
#- python setup.py sdist
#- pip install twine
#- twine upload --verbose --config-file .pypirc-bot -r pypi dist/*
before_install:
- openssl aes-256-cbc -K $encrypted_3bc2bd3e7847_key -iv $encrypted_3bc2bd3e7847_iv
  -in secret-files.tar.enc -out secret-files.tar -d
- tar xvf secret-files.tar
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $github_token
#  keep_history: true
#  local_dir: ontheroad_ui/build
#  on:
#    branch: master
#  with:
#    REACT_APP_HOST_IP: johnstratoudakis.com
